# list of the vagrant images provided by hashicorp
systems:
      - "hashicorp/precise32"
      - "ubuntu/trusty64"
      - "puphpet/centos65-x64"

# run any shell command when the VM boots
command: "python unittest.py"

# Example puppet files to pass to your Virtual Machines
puppet : 'init.pp'

# digital ocean sample usage
digital_ocean:
    id_rsa: 'id_rsa'
    image: 'ubuntu-14-04-x64'

# linode sample usage
linode:
    id_rsa: 'id_rsa'
    distro: 'Ubuntu 14.04 LTS'

# Debug Flag
debug: True
