# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

  config.vm.box = {{ load_os }}

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file  = "base.pp"
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  
  config.vm.provision "shell",
  inline: "{{ command  }}"

end
